#!/bin/bash
set -e

# Script to setup pre-requisites

# Must be run as root
if [[ `whoami` != "root" ]]
then
  echo "This install must be run as root or with sudo."
  exit
fi

echo ""

if grep -q \#dtparam=spi=on "/boot/config.txt"
then
   echo "Enabling SPI in /boot/config.txt"
   sed -i 's/#dtparam=spi=on/dtparam=spi=on/g' /boot/config.txt
else
   if grep -q dtparam=spi=on "/boot/config.txt"
   then
       echo "SPI already enabled in /boot/config.txt"
   else
       echo "Enabling SPI in /boot/config.txt"
cat - >> /boot/config.txt <<BOOTCONF
dtparam=spi=on
BOOTCONF
   fi   
fi

echo "Adding user pi to spi and gpio groups"
usermod -a -G spi,gpio pi

echo "Installing prerequisites"
apt-get install python3-dev python3-pip libfreetype6-dev libjpeg-dev build-essential -y
pip3 install --upgrade pip
pip3 install --upgrade luma.oled
pip3 install --upgrade requests

echo "Setup complete, now reboot to properly enable SPI driver, check it with lsmod | grep spi"
